const nav=document.querySelectorAll('nav button'),pages=document.querySelectorAll('.page'),title=document.querySelector('#title');let map,routeLayer,startMarker,endMarker;const cache=new Map();
const greeting=()=>{const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening'};
const names={home:greeting(),plan:'Plan your journey',check:'Your AURA Check-In',saved:'Places near you'};
function open(id){nav.forEach(x=>x.classList.toggle('active',x.dataset.page===id));pages.forEach(x=>x.classList.toggle('visible',x.id===id));title.textContent=names[id]}
function toast(message){const t=document.querySelector('.toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function injectScript(src){return new Promise((resolve,reject)=>{const e=document.createElement('script');e.src=src;e.onload=resolve;e.onerror=reject;document.head.appendChild(e)})}
async function initMap(){try{await injectScript('config.js');const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);await injectScript('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js');await injectScript('https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.js');
await injectScript('https://unpkg.com/@maplibre/maplibre-gl-leaflet/leaflet-maplibre-gl.js');const canvas=document.createElement('div');canvas.id='mapCanvas';document.querySelector('.map').prepend(canvas);map=L.map('mapCanvas').setView([12.9716,77.5946],12);L.maplibreGL({
    style: 'https://tiles.openfreemap.org/styles/liberty'
}).addTo(map);;document.querySelector('.map').classList.add('osm-ready')}catch{toast('OpenStreetMap could not load. Check your internet connection.')}}
async function geocode(query){if(cache.has(query))return cache.get(query);const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(query)}`);const d=await r.json();if(!d[0])throw Error();const point=[+d[0].lat,+d[0].lon];cache.set(query,point);return point}
async function route(startName,endName){if(!map){toast('Map is loading. Try again in a moment.');return}try{toast('Finding your live route…');const [a,b]=await Promise.all([geocode(startName),geocode(endName)]);const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${a[1]},${a[0]};${b[1]},${b[0]}?overview=full&geometries=geojson`);const d=await r.json(),trip=d.routes?.[0];if(!trip)throw Error();[routeLayer,startMarker,endMarker].forEach(x=>x&&map.removeLayer(x));routeLayer=L.geoJSON(trip.geometry,{style:{color:'#5e51cf',weight:6}}).addTo(map);startMarker=L.marker(a).addTo(map).bindPopup(`Start: ${startName}`);endMarker=L.marker(b).addTo(map).bindPopup(`Destination: ${endName}`);map.fitBounds(routeLayer.getBounds(),{padding:[45,45]});const min=Math.round(trip.duration/60),km=(trip.distance/1000).toFixed(1);document.querySelector('.next b').textContent=endName;document.querySelector('.next em').textContent=`Live route · ${min} min · ${km} km`;toast(`Live route ready · ${min} min · ${km} km`)}catch{toast('We could not find that route. Try a more specific place name.')}}
function addDetails(){document.querySelector('#departureTime').innerHTML='<option>Leave now</option><option>In 15 minutes</option><option>In 30 minutes</option><option>In 1 hour</option><option>Tonight · 9:00 PM</option><option>Tomorrow morning · 8:00 AM</option>';const cards='<div class="detail-grid"><div><span class="detail-icon">◷</span><b>Flexible departure</b><small>Choose a time that matches your plan. AURA refreshes context when you plan to leave.</small></div><div><span class="detail-icon">☼</span><b>Travel context</b><small>Weather and public-transit changes appear with your route.</small></div><div><span class="detail-icon">⌁</span><b>Route reasons</b><small>See time, distance, and recovery options before choosing.</small></div></div>';document.querySelector('#plan .feature').insertAdjacentHTML('afterend',cards);document.querySelector('#check .feature').insertAdjacentHTML('afterend',cards.replace('Flexible departure','Check-in schedule').replace('Travel context','Your support circle').replace('Route reasons','Quiet by default'));document.querySelector('#saved').insertAdjacentHTML('afterbegin','<div class="nearby-title"><div><p class="eyebrow">SAFE PLACE FINDER</p><h2>Places near you</h2></div><div><p id="nearbyStatus">Use your location to find public places close by.</p><button class="location-button" id="locateMe">Use my location</button></div></div>');document.querySelector('#saved>h2').remove()}
async function nearby(lat,lng){const status=document.querySelector('#nearbyStatus');status.textContent='Finding nearby public places…';try{const q=`[out:json][timeout:12];nwr[amenity~"cafe|pharmacy|hospital|police"](around:1500,${lat},${lng});out center 6;`;const r=await fetch(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(q)}`),d=await r.json();const places=d.elements.slice(0,3);if(!places.length)throw Error();document.querySelector('.list').innerHTML=places.map(p=>`<div>⌖ <p><b>${p.tags?.name||p.tags?.amenity||'Public place'}</b><small>${p.tags?.amenity||'place'} · near your location</small></p><button>View on map →</button></div>`).join('');status.textContent='Showing nearby public places from OpenStreetMap.'}catch{status.textContent='Could not find places right now. Try again shortly.'}}
title.textContent=names.home;nav.forEach(x=>x.onclick=()=>open(x.dataset.page));document.querySelector('#viewPlan').onclick=()=>open('plan');document.querySelector('#show').onclick=()=>{const a=document.querySelector('#startLocation').value.trim(),b=document.querySelector('#destinationLocation').value.trim();if(!a||!b){toast('Please add both locations.');return}open('home');route(a,b)};
const toggle=document.querySelector('#themeToggle');function theme(dark){document.body.classList.toggle('dark',dark);localStorage.setItem('auraTheme',dark?'dark':'light')}theme(localStorage.getItem('auraTheme')==='dark');toggle.onclick=()=>theme(!document.body.classList.contains('dark'));
document.querySelectorAll('[data-help]').forEach(button=>button.onclick=()=>{if(button.dataset.help==='stop')open('saved');else if(button.dataset.help==='check')open('check');else toast('Move to a busy, well-lit public place and open your Check-In options.')});document.querySelector('#schedule').onclick=()=>{document.querySelector('#label').textContent='Scheduled after your arrival';toast('Your AURA Check-In is scheduled.')};document.querySelectorAll('.routes button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.routes button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});addDetails();document.querySelector('#locateMe').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>nearby(p.coords.latitude,p.coords.longitude),()=>toast('Location permission was not granted.')):toast('Location is unavailable in this browser.');initMap();
